### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by tungv** [tvooo/scope-inspector#17] opened 2015-03-19 03:15 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/tung/Downloads/Atom.app/Contents/Resources/app/src/atom.js:54:11)
ScopeInspectorView.initialize (/Users/tung/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:16:9)
```

**Comment by tvooo** [comment] 2015-04-07 19:49
Thanks @tungv, I will look into it this weekend. This issue is a duplicate of #15

**Closed by tvooo** 2015-04-07 19:49 UTC
Labels: duplicate
