### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focusScope' of undefined

### ISSUE THREAD

**Issue by bytenel** [tvooo/scope-inspector#11] opened 2014-12-11 01:16 UTC
Uncaught TypeError: Cannot read property 'focusScope' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package, v0.2.1

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/bytenel/.atom/packages/scope-inspector/lib/scope-path-view.coffee:47

TypeError: Cannot read property 'focusScope' of undefined
  at ScopePathView.module.exports.ScopePathView.onLeaveButton (/Users/bytenel/.atom/packages/scope-inspector/lib/scope-path-view.coffee:47:29)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

/cc @atom/core

**Comment by tvooo** [comment] 2015-04-10 21:18
This should have been fixed by 0586fa52042efda1aef0f0d795a071bd6ca4581e, but I couldn't reproduce the error. Please reopen if this occurs again.

**Closed by tvooo** 2015-04-10 21:18 UTC
